mainimage=/usr/share/desktopwaifu/model3/henya_no_eyes.png
eyeimage=/usr/share/desktopwaifu/model3/animeye.png
mouseproximity=700
eye1x=790
eye2x=1018
eye1y=447
eye2y=441
eye1w=50
eye2w=50
eye1h=60
eye2h=60
replacergb=0

